# Pandas
1. Series (one-dimensional)
2. DataFrame ( two-dimensional)

In [1]:
a = [1,2,3] # one-dim

In [2]:
a = [
    [1,2,3],
    [2,3,4]
]

date         temp  wind sp
2024/02/02   30     44  2
2024/02/03   31     44  2
2024/02/04   31     44  2

In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-macosx_10_15_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/subhrat/Documents/teaching/ncc/python_class/.venv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/subhrat/Documents/teaching/ncc/python_class/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/subhrat/Documents/teaching/ncc/python_class/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-macosx_10_15_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 2.8 MB/s  0:00:03 eta 0:00:0136m0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [17]:
import pandas as pd
data = {
        'Name': ['John', 'Anna', 'Peter','Peter', 'Linda'],
        'Age': [28, 24, 35,None,32],
        'City': ['New York', 'Paris', 'Berlin','Berlin', 'London']
}

df = pd.DataFrame(data)
df.index

# axis = 0 Index
# axis = 1 Column

RangeIndex(start=0, stop=5, step=1)

In [16]:
df1 = pd.Series(
    ['John', 'Anna', 'Peter', 'Linda'],
    index=['a','b','c','d']
)
df1.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [4]:
df1[['a','b']]

a    John
b    Anna
dtype: str

In [19]:
df1.values

array(['John', 'Anna', 'Peter', 'Linda'], dtype=object)

In [27]:
df1 = pd.Series(
    [1,10,100,1000],
    index=['a','b','c','d']
)
df1

a       1
b      10
c     100
d    1000
dtype: int64

In [7]:
import pandas as pd
data = {
        'Name': ['John', 'Anna', 'Peter','Peter', 'Linda'],
        'Age': [28, 24, 35,None,32],
        'City': ['New York', 'Paris', 'Berlin','Berlin', 'London']
}

# 
df = pd.DataFrame(data)

In [9]:
new_df = df.rename(index={0:"new index 0"}, inplace=True)
df

              Name   Age      City
new index 0   John  28.0  New York
1             Anna  24.0     Paris
2            Peter  35.0    Berlin
3            Peter   NaN    Berlin
4            Linda  32.0    London

In [21]:
# df.rename(columns={"Name":"a"}, inplace=True)

In [31]:
# df.columns = ["Full Name","Age Value","City"]

In [39]:
df.columns

Index(['full name', 'age value', 'city'], dtype='object')

In [38]:
# c = []
# for a in df.columns:
#     c.append(a.lower())
# df.columns = c
# df

            full name  age value      city
new index 0      John       28.0  New York
1                Anna       24.0     Paris
2               Peter       35.0    Berlin
3               Peter        NaN    Berlin
4               Linda       32.0    London

In [19]:
import pandas as pd
data = {
        'Name': ['John', 'Anna', 'Peter','Peter', 'Linda','Hari', 'Ram','John', 'Anna', 'Peter','Peter', 'Linda','Hari','Ram','John', 'Anna', 'Peter','Peter', 'Linda','Hari', 'Ram','John', 'Anna', 'Peter','Peter', 'Linda','Hari','Ram'],
        'Age': [28, 24, 35,None,32,35,25,28, 24, 35,34,32,35,25,28, 24, 35,None,32,35,25,28, 24, 35,34,32,35,25],
        'City': ['New York', 'Paris', 'Berlin','Berlin', 'London','Nepal','Japan','New York', 'Paris', 'Berlin','Berlin', 'London','Nepal','Japan','New York', 'Paris', 'Berlin','Berlin', 'London','Nepal','Japan','New York', 'Paris', 'Berlin','Berlin', 'London','Nepal','Japan']
}

df = pd.DataFrame(data)
df.head()

    Name   Age      City
0   John  28.0  New York
1   Anna  24.0     Paris
2  Peter  35.0    Berlin
3  Peter   NaN    Berlin
4  Linda  32.0    London

In [12]:
df.tail()

              Name   Age      City
new index 0   John  28.0  New York
1             Anna  24.0     Paris
2            Peter  35.0    Berlin
3            Peter   NaN    Berlin
4            Linda  32.0    London

In [58]:
df.describe()

             Age
count  26.000000
mean   30.153846
std     4.505040
min    24.000000
25%    25.000000
50%    32.000000
75%    35.000000
max    35.000000

In [78]:
df.shape

(28, 3)

In [63]:
print(len(df))

28

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    28 non-null     str
 1   Age     26 non-null     float64
 2   City    28 non-null     str
dtypes: float64(1), str(2)
memory usage: 804.0 bytes

In [11]:
df[["Age","Name"]].head()

              Age   Name
new index 0  28.0   John
1            24.0   Anna
2            35.0  Peter
3             NaN  Peter
4            32.0  Linda

In [77]:
# function/class call or define ()
# accessing list of data [] df[""] df[["",""]]
df.head()

    Name   Age      City
0   John  28.0  New York
1   Anna  24.0     Paris
2  Peter  35.0    Berlin
3  Peter   NaN    Berlin
4  Linda  32.0    London

In [1]:
import pandas as pd
df = pd.read_csv(r'train.csv')

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [11]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [13]:
df1 = df[["Name","Age"]]
df1.head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [14]:
df.iloc[50:61]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.0,0,0,A/4. 39886,7.8000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.0,1,0,2926,26.0000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
56,57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,NaN,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,NaN,S
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9000,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C

In [15]:
df[df['Age'] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [16]:
df[df.Age > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [17]:
df.drop(columns=["Embarked"],inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN

In [28]:
df.drop(columns=["Cabin"],inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [18]:
df1=df.dropna(axis=0, how='all', subset=['Age','Cabin'])
df1.info()

<class 'pandas.DataFrame'>
Index: 733 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  733 non-null    int64
 1   Survived     733 non-null    int64
 2   Pclass       733 non-null    int64
 3   Name         733 non-null    str
 4   Sex          733 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        733 non-null    int64
 7   Parch        733 non-null    int64
 8   Ticket       733 non-null    str
 9   Fare         733 non-null    float64
 10  Cabin        204 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 68.7 KB

In [19]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [27]:
# !pip install openpyxl
df.to_excel('titanic.xlsx')

In [28]:
df_new = pd.read_excel(r'titanic.xlsx')
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    str
 5   Sex          891 non-null    str
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    str
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    str
dtypes: float64(2), int64(6), str(4)
memory usage: 83.7 KB

In [31]:
df_new = pd.read_excel(r'check.xlsx',dtype={"UniqueCustomerID":str, "BranchCode":str,"AccountNo":str})
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SNO                 7 non-null      int64
 1   S                   7 non-null      int64
 2   BranchCode          7 non-null      str
 3   Product             7 non-null      str
 4   AccountNo           7 non-null      str
 5   AccountName         7 non-null      str
 6   AccountOpeningDate  7 non-null      datetime64[us]
 7   MonthEndBaln        7 non-null      float64
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 580.0 bytes

In [86]:
df_new.head(10)

,SNO,UniqueCustomerID,BranchCode,Product,AccountNo,AccountName,AccountOpeningDate,MonthEndBaln
0,1,00000002,001,SAVING,100600000007000001,Ram,2006-07-31,10357.44
1,2,00000003,001,SAVING,100600000008000001,Shyam,2006-07-31,1128.79
2,3,00000004,001,SAVING,100600000002000001,hari,2006-07-31,6045.53
3,4,00000005,001,SAVING,100600000003000001,geeta,2006-07-31,1617.19
4,5,00000006,001,SAVING,100600000004000001,Manish,2006-07-31,2.62
5,6,00000007,001,SAVING,100600000005000001,bijesh,2006-07-31,44207.32
6,7,00000008,001,SAVING,100600000006000001,santosh,2006-07-31,2155.52

In [32]:
df_new = pd.read_excel('check.xlsx')
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SNO                 7 non-null      int64
 1   S                   7 non-null      int64
 2   BranchCode          7 non-null      int64
 3   Product             7 non-null      str
 4   AccountNo           7 non-null      int64
 5   AccountName         7 non-null      str
 6   AccountOpeningDate  7 non-null      datetime64[us]
 7   MonthEndBaln        7 non-null      float64
dtypes: datetime64[us](1), float64(1), int64(4), str(2)
memory usage: 580.0 bytes