In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
data={
      'Name':['Dinesh','Ramesh','Nirpesh','mohan','Hari','New york','Paris','Berlin','Berlin','london'],
    'Age':[28,24,35,None,32,28,24,35,None,32],
    'City':['New york','Paris','Berlin','Berlin','london','New york','Paris','Berlin','Berlin','london']
}
df = pd.DataFrame(data)
df

       Name   Age      City
0    Dinesh  28.0  New york
1    Ramesh  24.0     Paris
2   Nirpesh  35.0    Berlin
3     mohan   NaN    Berlin
4      Hari  32.0    london
5  New york  28.0  New york
6     Paris  24.0     Paris
7    Berlin  35.0    Berlin
8    Berlin   NaN    Berlin
9    london  32.0    london

In [4]:
df1 = pd.Series(
    ['John','Anna','Peter','Linda'],
    index = ['a','b','c','d']
)
df1.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [5]:
new_df = df.rename(index={0:"new index 0"}, inplace= True)
df

                 Name   Age      City
new index 0    Dinesh  28.0  New york
1              Ramesh  24.0     Paris
2             Nirpesh  35.0    Berlin
3               mohan   NaN    Berlin
4                Hari  32.0    london
5            New york  28.0  New york
6               Paris  24.0     Paris
7              Berlin  35.0    Berlin
8              Berlin   NaN    Berlin
9              london  32.0    london

In [6]:
df. columns

Index(['Name', 'Age', 'City'], dtype='str')

In [7]:
'''Head & Tail'''

'Head & Tail'

In [8]:

df.head(-2)

                 Name   Age      City
new index 0    Dinesh  28.0  New york
1              Ramesh  24.0     Paris
2             Nirpesh  35.0    Berlin
3               mohan   NaN    Berlin
4                Hari  32.0    london
5            New york  28.0  New york
6               Paris  24.0     Paris
7              Berlin  35.0    Berlin

In [9]:
df.shape
#It shows number of rows and column in dataframe

(10, 3)

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, new index 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     8 non-null      float64
 2   City    10 non-null     str
dtypes: float64(1), str(2)
memory usage: 320.0+ bytes